import type {
  Account,
  CampaignTouch,
  DocumentRecord,
  Intervention,
  Lot,
} from "./types";

export const LOTS: Lot[] = [
  {
    id: "vn-future-farm-082",
    farm: "Future Farm",
    producer: "Toi Nguyen",
    origin: "Dak Lak, Vietnam",
    region: "Central Highlands",
    country: "Vietnam",
    varietal: "Fine Robusta",
    species: "Coffea canephora",
    process: "washed",
    elevationM: 720,
    cupScore: 82.75,
    moisture: 11.4,
    waterActivity: 0.54,
    pricePerLbCents: 570,
    costPerLbCents: 300,
    availableLbs: 2640,
    bags: 40,
    harvest: "2026",
    eta: "12 Oct 2026",
    flavor: ["cocoa", "cedar", "brown sugar", "black pepper"],
    esg: 81,
    logistics: 74,
    certifications: ["4C", "EUDR file"],
    supplierId: "acc-chex",
    sampleId: "VN-2026-0827",
  },
  {
    id: "vn-vuong-java-086",
    farm: "Vuong Family Farms",
    producer: "Vuong family",
    origin: "Lac Duong, Vietnam",
    region: "Lam Dong",
    country: "Vietnam",
    varietal: "Java",
    species: "Coffea arabica var. Java",
    process: "washed",
    elevationM: 1480,
    cupScore: 86.0,
    moisture: 10.9,
    waterActivity: 0.52,
    pricePerLbCents: 800,
    costPerLbCents: 410,
    availableLbs: 1320,
    bags: 20,
    harvest: "2026",
    eta: "04 Nov 2026",
    flavor: ["jasmine", "bergamot", "cane sugar", "stone fruit"],
    esg: 88,
    logistics: 69,
    certifications: ["Organic", "EUDR file"],
    supplierId: "acc-chex",
    sampleId: "VN-2026-0860",
  },
  {
    id: "vn-kho-honey-084",
    farm: "K'Ho Cooperative",
    producer: "K'Ho Co-op",
    origin: "Lac Duong, Vietnam",
    region: "Lam Dong",
    country: "Vietnam",
    varietal: "Catimor",
    species: "Coffea arabica",
    process: "honey",
    elevationM: 1550,
    cupScore: 84.5,
    moisture: 11.1,
    waterActivity: 0.53,
    pricePerLbCents: 640,
    costPerLbCents: 335,
    availableLbs: 1980,
    bags: 30,
    harvest: "2026",
    eta: "18 Oct 2026",
    flavor: ["guava", "honey", "cacao nib", "floral"],
    esg: 91,
    logistics: 62,
    certifications: ["Fair Trade", "Bird-Friendly"],
    supplierId: "acc-kho",
    sampleId: "VN-2026-0845",
  },
  {
    id: "vn-caudat-gesha-090",
    farm: "Cau Dat Station",
    producer: "Da Lat Research Plot",
    origin: "Cau Dat, Vietnam",
    region: "Lam Dong",
    country: "Vietnam",
    varietal: "Gesha",
    species: "Coffea arabica",
    process: "washed",
    elevationM: 1650,
    cupScore: 90.5,
    moisture: 10.6,
    waterActivity: 0.51,
    pricePerLbCents: 1840,
    costPerLbCents: 920,
    availableLbs: 396,
    bags: 6,
    harvest: "2026",
    eta: "22 Nov 2026",
    flavor: ["jasmine", "bergamot", "white peach", "honey"],
    esg: 86,
    logistics: 58,
    certifications: ["Organic"],
    supplierId: "acc-sih",
    sampleId: "VN-2026-0905",
  },
  {
    id: "vn-eahleo-rob-081",
    farm: "Ea H'leo Block",
    producer: "Collector network",
    origin: "Ea H'leo, Vietnam",
    region: "Dak Lak",
    country: "Vietnam",
    varietal: "Robusta",
    species: "Coffea canephora",
    process: "washed",
    elevationM: 580,
    cupScore: 81.25,
    moisture: 11.8,
    waterActivity: 0.55,
    pricePerLbCents: 420,
    costPerLbCents: 300,
    availableLbs: 5280,
    bags: 80,
    harvest: "2026",
    eta: "02 Oct 2026",
    flavor: ["dark chocolate", "walnut", "earth"],
    esg: 72,
    logistics: 81,
    certifications: ["4C"],
    supplierId: "acc-chex",
    sampleId: "VN-2026-0812",
    claimedScore: 84,
  },
  {
    id: "vn-dalat-ana-085",
    farm: "Da Lat Anaerobic Cellar",
    producer: "Nguyen sisters",
    origin: "Da Lat, Vietnam",
    region: "Lam Dong",
    country: "Vietnam",
    varietal: "Bourbon",
    species: "Coffea arabica",
    process: "anaerobic",
    elevationM: 1500,
    cupScore: 85.5,
    moisture: 11.0,
    waterActivity: 0.52,
    pricePerLbCents: 920,
    costPerLbCents: 480,
    availableLbs: 792,
    bags: 12,
    harvest: "2026",
    eta: "09 Nov 2026",
    flavor: ["tropical", "winey", "cocoa", "clove"],
    esg: 79,
    logistics: 64,
    certifications: ["EUDR file"],
    supplierId: "acc-sih",
    sampleId: "VN-2026-0855",
  },
  {
    id: "et-sidama-nat-087",
    farm: "Bensa smallholders",
    producer: "Bensa union",
    origin: "Sidama, Ethiopia",
    region: "Sidama",
    country: "Ethiopia",
    varietal: "Heirloom",
    species: "Coffea arabica",
    process: "natural",
    elevationM: 1950,
    cupScore: 87.75,
    moisture: 10.8,
    waterActivity: 0.52,
    pricePerLbCents: 760,
    costPerLbCents: 390,
    availableLbs: 1848,
    bags: 28,
    harvest: "2025/26",
    eta: "28 Sep 2026",
    flavor: ["blueberry", "jasmine", "bergamot", "cocoa"],
    esg: 84,
    logistics: 71,
    certifications: ["Organic", "Rainforest Alliance"],
    supplierId: "acc-sih",
    sampleId: "ET-2026-0877",
  },
  {
    id: "co-huila-wash-086",
    farm: "Finca La Palma",
    producer: "Restrepo family",
    origin: "Huila, Colombia",
    region: "Huila",
    country: "Colombia",
    varietal: "Caturra",
    species: "Coffea arabica",
    process: "washed",
    elevationM: 1750,
    cupScore: 86.25,
    moisture: 11.2,
    waterActivity: 0.53,
    pricePerLbCents: 520,
    costPerLbCents: 280,
    availableLbs: 2376,
    bags: 36,
    harvest: "2026",
    eta: "15 Oct 2026",
    flavor: ["panela", "red apple", "cocoa", "floral"],
    esg: 83,
    logistics: 77,
    certifications: ["Rainforest Alliance"],
    supplierId: "acc-sih",
    sampleId: "CO-24-A01",
  },
  {
    id: "vn-gialai-nat-080",
    farm: "Gia Lai Natural Yard",
    producer: "Unlinked lots",
    origin: "Gia Lai, Vietnam",
    region: "Gia Lai",
    country: "Vietnam",
    varietal: "Robusta",
    species: "Coffea canephora",
    process: "natural",
    elevationM: 620,
    cupScore: 80.5,
    moisture: 12.4,
    waterActivity: 0.58,
    pricePerLbCents: 380,
    costPerLbCents: 300,
    availableLbs: 3960,
    bags: 60,
    harvest: "2026",
    eta: "08 Oct 2026",
    flavor: ["dried fruit", "wood", "cocoa"],
    esg: 61,
    logistics: 70,
    certifications: [],
    supplierId: "acc-newco",
    sampleId: "VN-2026-0805",
    claimedScore: 86,
  },
  {
    id: "vn-lamdong-carb-088",
    farm: "Lang Biang Cell",
    producer: "Lam Dong station",
    origin: "Lac Duong, Vietnam",
    region: "Lam Dong",
    country: "Vietnam",
    varietal: "Typica",
    species: "Coffea arabica",
    process: "carbonic",
    elevationM: 1580,
    cupScore: 88.25,
    moisture: 10.7,
    waterActivity: 0.51,
    pricePerLbCents: 1280,
    costPerLbCents: 640,
    availableLbs: 528,
    bags: 8,
    harvest: "2026",
    eta: "01 Dec 2026",
    flavor: ["lychee", "rose", "cocoa", "lime"],
    esg: 85,
    logistics: 60,
    certifications: ["Organic", "EUDR file"],
    supplierId: "acc-kho",
    sampleId: "VN-2026-0882",
  },
];

export const ACCOUNTS: Account[] = [
  {
    id: "acc-atlas",
    name: "Atlas Roasting Co.",
    kind: "roaster",
    segment: "boutique",
    size: "9 staff · 1,400 lb/mo",
    city: "Portland",
    country: "USA",
    contact: "Mira Chen",
    email: "mira@atlasroast.example",
    lifecycle: "active",
    churnRisk: 0.18,
    ltvCents: 2140000,
    cacCents: 37800,
    lastActivity: "2026-08-29",
    kits: 6,
    orders: 11,
    engagements6mo: 14,
    daysSinceOrder: 18,
    paybackMonths: 4,
  },
  {
    id: "acc-harbor",
    name: "Harbor Microroaster",
    kind: "roaster",
    segment: "micro",
    size: "3 staff · 280 lb/mo",
    city: "Halifax",
    country: "Canada",
    contact: "Eli Park",
    email: "eli@harbor.example",
    lifecycle: "trial",
    churnRisk: 0.41,
    ltvCents: 420000,
    cacCents: 25000,
    lastActivity: "2026-08-21",
    kits: 1,
    orders: 0,
    engagements6mo: 4,
    daysSinceOrder: 999,
    paybackMonths: 9,
  },
  {
    id: "acc-northline",
    name: "Northline Coffee",
    kind: "roaster",
    segment: "commercial",
    size: "4 sites · 6,200 lb/mo",
    city: "Chicago",
    country: "USA",
    contact: "Dana Ruiz",
    email: "dana@northline.example",
    lifecycle: "dormant",
    churnRisk: 0.76,
    ltvCents: 9100000,
    cacCents: 250000,
    lastActivity: "2026-05-12",
    kits: 8,
    orders: 19,
    engagements6mo: 2,
    daysSinceOrder: 108,
    paybackMonths: 7,
  },
  {
    id: "acc-saigon",
    name: "Saigon Cup Lab",
    kind: "roaster",
    segment: "boutique",
    size: "7 staff · 900 lb/mo",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    contact: "Linh Tran",
    email: "linh@saigoncup.example",
    lifecycle: "active",
    churnRisk: 0.22,
    ltvCents: 1680000,
    cacCents: 31000,
    lastActivity: "2026-08-30",
    kits: 4,
    orders: 7,
    engagements6mo: 11,
    daysSinceOrder: 9,
    paybackMonths: 3,
  },
  {
    id: "acc-chex",
    name: "Central Highlands Exporters",
    kind: "exporter",
    segment: "supply",
    size: "28 containers/yr",
    city: "Buon Ma Thuot",
    country: "Vietnam",
    contact: "Pham Duc",
    email: "duc@chex.example",
    lifecycle: "active",
    churnRisk: 0.11,
    ltvCents: 18600000,
    cacCents: 300000,
    lastActivity: "2026-08-31",
    kits: 22,
    orders: 41,
    engagements6mo: 18,
    daysSinceOrder: 4,
    paybackMonths: 5,
  },
  {
    id: "acc-sih",
    name: "Saigon Import House",
    kind: "import_house",
    segment: "supply",
    size: "44 lots · 3 reps",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    contact: "Hanh Vo",
    email: "hanh@sih.example",
    lifecycle: "active",
    churnRisk: 0.09,
    ltvCents: 42000000,
    cacCents: 430000,
    lastActivity: "2026-08-31",
    kits: 31,
    orders: 64,
    engagements6mo: 21,
    daysSinceOrder: 2,
    paybackMonths: 6,
  },
  {
    id: "acc-kho",
    name: "K'Ho Highland Co-op",
    kind: "exporter",
    segment: "supply",
    size: "12 containers/yr",
    city: "Lac Duong",
    country: "Vietnam",
    contact: "Y K'Brieng",
    email: "kbrieng@kho.example",
    lifecycle: "active",
    churnRisk: 0.15,
    ltvCents: 6400000,
    cacCents: 180000,
    lastActivity: "2026-08-28",
    kits: 9,
    orders: 14,
    engagements6mo: 10,
    daysSinceOrder: 12,
    paybackMonths: 5,
  },
  {
    id: "acc-newco",
    name: "Newco Yard Brokers",
    kind: "trader",
    segment: "supply",
    size: "Unverified desk",
    city: "Gia Lai",
    country: "Vietnam",
    contact: "Desk unassigned",
    email: "desk@newco.example",
    lifecycle: "trial",
    churnRisk: 0.62,
    ltvCents: 210000,
    cacCents: 90000,
    lastActivity: "2026-07-02",
    kits: 0,
    orders: 1,
    engagements6mo: 1,
    daysSinceOrder: 64,
    paybackMonths: 14,
  },
];

export const DOCUMENTS: DocumentRecord[] = [
  {
    id: "doc-001",
    type: "sca_lab_report",
    status: "accepted",
    lotId: "vn-vuong-java-086",
    accountId: "acc-chex",
    filename: "SCA-Vuong-Java-086.pdf",
    createdAt: "2026-08-12",
    confidence: 0.94,
    fields: {
      sampleId: { value: "VN-2026-0860", confidence: 0.97 },
      cupScore: { value: "86.0", confidence: 0.96 },
      moisture: { value: "10.9", confidence: 0.91 },
    },
  },
  {
    id: "doc-002",
    type: "certificate_of_origin",
    status: "accepted",
    lotId: "vn-vuong-java-086",
    accountId: "acc-chex",
    filename: "CoO-LamDong-086.pdf",
    createdAt: "2026-08-14",
    confidence: 0.91,
    fields: {
      origin: { value: "Vietnam · Lam Dong", confidence: 0.93 },
      quantity: { value: "20 bags", confidence: 0.88 },
    },
  },
  {
    id: "doc-003",
    type: "sca_lab_report",
    status: "accepted",
    lotId: "vn-future-farm-082",
    accountId: "acc-chex",
    filename: "CQI-FutureFarm-082.pdf",
    createdAt: "2026-08-08",
    confidence: 0.89,
    fields: {
      sampleId: { value: "VN-2026-0827", confidence: 0.92 },
      cupScore: { value: "82.75", confidence: 0.9 },
    },
  },
  {
    id: "doc-004",
    type: "contract",
    status: "accepted",
    lotId: "co-huila-wash-086",
    accountId: "acc-sih",
    filename: "Contract-LaPalma-A01.pdf",
    createdAt: "2026-08-20",
    confidence: 0.87,
    fields: {
      volume: { value: "36 bags", confidence: 0.86 },
      unitPrice: { value: "$5.20/lb", confidence: 0.84 },
    },
  },
  {
    id: "doc-005",
    type: "phytosanitary",
    status: "accepted",
    lotId: "vn-kho-honey-084",
    accountId: "acc-kho",
    filename: "Phyto-KHo-084.pdf",
    createdAt: "2026-08-18",
    confidence: 0.9,
    fields: {
      certNo: { value: "VN-PP-44119", confidence: 0.93 },
    },
  },
  {
    id: "doc-006",
    type: "warehouse_receipt",
    status: "review",
    lotId: "vn-gialai-nat-080",
    accountId: "acc-newco",
    filename: "WH-GiaLai-080.jpg",
    createdAt: "2026-08-30",
    confidence: 0.61,
    fields: {
      bags: { value: "60", confidence: 0.55 },
      weight: { value: "unclear", confidence: 0.41 },
    },
  },
];

export const INTERVENTIONS: Intervention[] = [
  {
    id: "int-1",
    accountId: "acc-northline",
    type: "sales_call",
    started: "2026-08-04",
    outcome: "pending",
  },
  {
    id: "int-2",
    accountId: "acc-harbor",
    type: "email_campaign",
    started: "2026-08-22",
    outcome: "pending",
  },
];

export const CAMPAIGNS: CampaignTouch[] = [
  {
    id: "c1",
    accountId: "acc-harbor",
    code: "COF-001",
    status: "opened",
    at: "2026-08-22",
  },
  {
    id: "c2",
    accountId: "acc-harbor",
    code: "COF-002",
    status: "queued",
    at: "2026-09-02",
  },
  {
    id: "c3",
    accountId: "acc-atlas",
    code: "COF-005",
    status: "converted",
    at: "2026-07-11",
  },
  {
    id: "c4",
    accountId: "acc-northline",
    code: "COF-004",
    status: "sent",
    at: "2026-08-05",
  },
  {
    id: "c5",
    accountId: "acc-saigon",
    code: "COF-003",
    status: "clicked",
    at: "2026-08-19",
  },
];

export const DOC_LABEL: Record<string, string> = {
  sca_lab_report: "SCA / Q lab report",
  contract: "Contract of sale",
  phytosanitary: "Phytosanitary certificate",
  certificate_of_origin: "Certificate of origin",
  warehouse_receipt: "Warehouse receipt",
  invoice: "Commercial invoice",
  cupping_form: "Cupping form",
  packing_list: "Packing list",
};

export const TRUE_PRICE_FLOOR_CENTS = 300;
