/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as TheCraftRouteImport } from './routes/the-craft'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as CrmAccountIdRouteImport } from './routes/crm.$accountId'
import { Route as LedgerLotIdRouteImport } from './routes/ledger.$lotId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const TheCraftRoute = TheCraftRouteImport.update({
  id: '/the-craft',
  path: '/the-craft',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmAccountIdRoute = CrmAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => CrmRoute,
} as any)
const LedgerLotIdRoute = LedgerLotIdRouteImport.update({
  id: '/$lotId',
  path: '/$lotId',
  getParentRoute: () => LedgerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/ecosystem': typeof EcosystemRoute
  '/ledger': typeof LedgerRouteWithChildren
  '/scan': typeof ScanRoute
  '/the-craft': typeof TheCraftRoute
  '/trust': typeof TrustRoute
  '/crm/$accountId': typeof CrmAccountIdRoute
  '/ledger/$lotId': typeof LedgerLotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/ecosystem': typeof EcosystemRoute
  '/ledger': typeof LedgerRouteWithChildren
  '/scan': typeof ScanRoute
  '/the-craft': typeof TheCraftRoute
  '/trust': typeof TrustRoute
  '/crm/$accountId': typeof CrmAccountIdRoute
  '/ledger/$lotId': typeof LedgerLotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/ecosystem': typeof EcosystemRoute
  '/ledger': typeof LedgerRouteWithChildren
  '/scan': typeof ScanRoute
  '/the-craft': typeof TheCraftRoute
  '/trust': typeof TrustRoute
  '/crm/$accountId': typeof CrmAccountIdRoute
  '/ledger/$lotId': typeof LedgerLotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm'
    | '/ecosystem'
    | '/ledger'
    | '/scan'
    | '/the-craft'
    | '/trust'
    | '/crm/$accountId'
    | '/ledger/$lotId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crm'
    | '/ecosystem'
    | '/ledger'
    | '/scan'
    | '/the-craft'
    | '/trust'
    | '/crm/$accountId'
    | '/ledger/$lotId'
  id:
    | '__root__'
    | '/'
    | '/crm'
    | '/ecosystem'
    | '/ledger'
    | '/scan'
    | '/the-craft'
    | '/trust'
    | '/crm/$accountId'
    | '/ledger/$lotId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmRoute: typeof CrmRouteWithChildren
  EcosystemRoute: typeof EcosystemRoute
  LedgerRoute: typeof LedgerRouteWithChildren
  ScanRoute: typeof ScanRoute
  TheCraftRoute: typeof TheCraftRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-craft': {
      id: '/the-craft'
      path: '/the-craft'
      fullPath: '/the-craft'
      preLoaderRoute: typeof TheCraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/$accountId': {
      id: '/crm/$accountId'
      path: '/$accountId'
      fullPath: '/crm/$accountId'
      preLoaderRoute: typeof CrmAccountIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/ledger/$lotId': {
      id: '/ledger/$lotId'
      path: '/$lotId'
      fullPath: '/ledger/$lotId'
      preLoaderRoute: typeof LedgerLotIdRouteImport
      parentRoute: typeof LedgerRoute
    }
  }
}

interface CrmRouteChildren {
  CrmAccountIdRoute: typeof CrmAccountIdRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmAccountIdRoute: CrmAccountIdRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface LedgerRouteChildren {
  LedgerLotIdRoute: typeof LedgerLotIdRoute
}

const LedgerRouteChildren: LedgerRouteChildren = {
  LedgerLotIdRoute: LedgerLotIdRoute,
}

const LedgerRouteWithChildren =
  LedgerRoute._addFileChildren(LedgerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmRoute: CrmRouteWithChildren,
  EcosystemRoute: EcosystemRoute,
  LedgerRoute: LedgerRouteWithChildren,
  ScanRoute: ScanRoute,
  TheCraftRoute: TheCraftRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
